
language: java

jdk:
    - oraclejdk6
    - oraclejdk7

branches:
  only:
    - master

before_script:
    - chmod +x grailsw
    - ./grailsw clean
    - ./grailsw refresh-dependencies
    - ./grailsw compile

script: ./grailsw test-app
